module.exports = {
  theme: {
    colors: {
      transparent: "transparent",
      shark: "#212529",
      celeste: "#cfd0ce",
      cararra: "#e9eae7",
      white: "#ffffff",
      apple: "#6db943",
      "alert-red": "#f31431",
      "warning-yellow": "#ffae42",
      "camouflage-green": "#757773",
      "curious-blue": "#398cd3",
      astronaut: "#255375",

      "bright-gray":  "#f1f4f4",
      "medium-gray":  "#8c9d96",
      "dark-gray":    "#4a4a4a",
      "light-green":  "#dbf8eb",
      "bright-green": "#008943",
      "dark-green":   "#006632",
      "deep-green":   "#003d1e",
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '9': '2.25rem',
      '10': '2.5rem',
      '12': '3rem',
      '14': '3.5rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '30': '7.5rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    backgroundColor: theme => theme('colors'),
    fontFamily: {
      heading: ["Montserrat", "system-ui", "-apple-system", "sans-serif",],
      body: ["Noto Sans", "system-ui", "-apple-system", "sans-serif",],
    },
    fontSize: {
      "2xs": ".625rem",  // 10px
      xs: ".75rem",      // 12px
      sm: ".875rem",     // 14px
      base: "1rem",      // 16px
      lg: "1.125rem",    // 18px
      xl: "1.25rem",     // 20px
      "2xl": "1.5rem",   // 24px
      "3xl": "1.875rem", // 30px
      "4xl": "2.25rem",  // 36px
      "5xl": "2.625rem", // 42px
      "6xl": "4rem",     // 64px
    },
    borderWidth: {
      default: "1px",
      "0": "0",
      "2": "2px",
      "4": "4px",
      "8": "8px",
    },
    minHeight: {
      "2-1/2": "10rem",
      "4": "16rem",
      "5-1/2": "21.5rem",
    },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      half: "50%",
      full: '100%',
      screen: '100vh',
    }),
    maxHeight: {
      full: "100%",
      screen: "100vh",
    },
    width: theme =>({
      auto: "auto",
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      full: "100%",
      screen: "100vw",
    }),
    maxWidth: {
      xs: "20rem",
      sm: "30rem",
      md: "40rem",
      lg: "50rem",
      xl: "60rem",
      "2xl": "70rem",
      "3xl": "80rem",
      "4xl": "90rem",
      "5xl": "100rem",
      full: "100%",
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    padding: theme => theme('spacing'),
    boxShadow: {
      default: "0 1px 2px 0 rgba(0,0,0,.325)",
      md: "0 4px 8px 0 rgba(0,0,0,.12), 0 2px 4px 0 rgba(0,0,0,0.8)",
      lg: "0 15px 30px 0 rgba(0,0,0,.11), 0 5px 15px 0 rgba(0,0,0,.08)",
      btn: "0 2px 6px 2px #E4E6E3, 0 3px 7px 1px #DBF8EB",
      inner: "inset 0 2px 4px 0 rgba(0,0,0,0.06)",
      outline: "0 0 0 3px rgba(theme('colors.dark-green'),1)",
      none: "none",
    },
    zIndex: {
      auto: "auto",
      "neg-10": -10,
      "0": 0,
      "10": 10,
      "20": 20,
      "30": 30,
      "40": 40,
      "50": 50,
      "60": 60,
      "70": 70,
    },
    opacity: {
      "0": "0",
      "3": ".03",
      "6": ".06",
      "12": ".12",
      "25": ".25",
      "50": ".5",
      "75": ".75",
      "100": "1",
    },
    container: theme => ({
      center: true,
    }),
  },
  variants: {
    appearance: ["responsive"],
    backgroundAttachment: ["responsive"],
    backgroundColor: ["responsive", "hover", "group-hover", "focus"],
    backgroundPosition: ["responsive"],
    backgroundRepeat: ["responsive"],
    backgroundSize: ["responsive"],
    borderCollapse: [],
    borderColor: ["responsive", "hover", "group-hover", "focus"],
    borderRadius: ["responsive", "hover", "group-hover"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive"],
    cursor: ["responsive"],
    display: ["responsive"],
    flexDirection: ["responsive"],
    flexWrap: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    justifyContent: ["responsive"],
    alignContent: ["responsive"],
    flex: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    float: ["responsive"],
    fontFamily: ["responsive"],
    fontWeight: ["responsive", "hover", "group-hover", "focus"],
    height: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: ["responsive"],
    listStyleType: ["responsive"],
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    negativeMargin: ["responsive"],
    opacity: ["responsive", "hover", "group-hover"],
    outline: ["focus"],
    overflow: ["responsive"],
    padding: ["responsive"],
    pointerEvents: ["responsive"],
    position: ["responsive"],
    inset: ["responsive"],
    resize: ["responsive"],
    boxShadow: ["responsive", "hover", "group-hover", "focus"],
    fill: [],
    stroke: [],
    tableLayout: ["responsive"],
    textAlign: ["responsive"],
    textColor: ["responsive", "hover", "group-hover", "focus"],
    fontSize: ["responsive"],
    fontStyle: ["responsive", "hover", "group-hover", "focus"],
    fontSmoothing: ["responsive", "hover", "group-hover", "focus"],
    textDecoration: ["responsive", "hover", "group-hover", "focus"],
    textTransform: ["responsive", "hover", "group-hover", "focus"],
    letterSpacing: ["responsive"],
    userSelect: ["responsive"],
    verticalAlign: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    wordBreak: ["responsive"],
    width: ["responsive"],
    zIndex: ["responsive"],
  },
  plugins: [
    require('tailwindcss-multi-column')(), // no options to configure
    require('tailwindcss-owl')()
  ],
};
